---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp-deploy
  labels:
    app: MyApp 
    env: prod
spec:
  selector:
    matchLabels:
      app: MyApp
  replicas: 2
  template:
    metadata:
      name: MyApp-pod
      labels:
        app: MyApp
        env: prod
        version: 1.3.0
    spec:
      containers:
        - name: MyApp-cnt
          image: maheshkumar010/project:13
          ports:
            - containerPort: 8080

---
apiVersion: v1 
kind: Service
metadata:
  name: MyApp-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: MyApp
    